### ISSUE TITLE
Add datasetkey to sources

### ISSUE THREAD

**Issue by damianooldoni** [inbo/speciesbim#19]
@peterdesmet proposes to add datasetKey (or complete DOI) as additional field in table `vernacularname`.

example, where the proposed column is in bold

id | taxonomyId | language | name | source | datasetKey
-- | -- | -- | -- | -- | --
26 | 34 | nl | geleedpotigen | World Register of Marine Species | **2d59e5db-57ad-41ff-97d6-11f5fb264527**
27 | 35 | nl | insecten | Belgian Species List | **39653f3e-8d6b-4a94-a202-859359c164c5**
28 | 35 | fr | insectes | Integrated Taxonomic Information System (ITIS) | **9ca92552-f23a-41a8-a140-01abaa31c931**

The datasetKey values could be retrieved after selecting the unique values in source. Then we can use pygbif module registry:

```python
from pygbif import registry
from helpers import get_config, execute_sql_from_jinja_string, get_database_connection

connection = get_database_connection()
    config = get_config()
    source_selection_sql = """SELECT DISTINCT source FROM vernacularname;"""
    cur = execute_sql_from_jinja_string(conn=connection, sql_string=source_selection_sql, context={}, dict_cursor=True)
    datasets = {}
    for source in cur:
        print(source)
        dataset_title = source['source']
        print(dataset_title)
        dataset = registry.dataset_suggest(dataset_title)
        datasetKey = dataset[0]['key']
        datasets[dataset_title] = datasetKey
    print(datasets)
```

**Comment by peterdesmet** [comment]
Oh, I now notice that the GBIF api is merely returning a string value for source, e.g. `Catalogue of Life` and not the datasetKey. Which means we need to do a second call, ideally over the whole table, to look those up (and store them in that or a separate table). That's not worth the effort, except if those links are absolutely required for a BIM application.

Let's ask BIM if this is necessary.

**Comment by damianooldoni** [comment]
Indeed, source is just a string, no datasetKey returned. We have 50 different `source` values up to now. Some more if the bug in #23 will be solved by GBIF.

**Comment by peterdesmet** [comment]
Decision is to store GBIF datasetKey in `source` and with a relation to a separate table `vernacularnamesource` that lists the title as well.

**Comment by damianooldoni** [comment]
@niconoe: if you agree, I can do this and you can review it?

**Comment by damianooldoni** [comment]
I worked on this just now (see relatd PR) and as we did for rank, we should not store dataset keys in `source` but the `id` of the row in `vernacularnamesource` where the information about the dataset (key and title) is stored. Same as we did also in taxonomy table, where we didn't use the GBIF key as `id`. 

Something like this example below:

id | taxonomyId | language | name | source
-- | -- | --- | -- | ---
1 | 1 | fr | champignons | 1
2 | 1 | en | fungi | 1
3 | 1 | nl | schimmels | 3
4 | 1 | en | fungi | 4
5 | 1 | en | fungi | 5
6 | 2 | en | asco's | 1
7 | 2 | en | ascomycetes | 1
8 | 2 | fr | ascomycètes | 1
9 | 2 | en | sac fungi | 1
10 | 2 | en | ascomycete fungi | 5
11 | 2 | en | ascomycete fungi | 4
12 | 2 | en | sac fungi | 4
13 | 2 | en | sac fungi | 5

And `vernacularnamesource `looks like:

id | datasetKey | datasetTitle
-- | -- | --
1 | 9ca92552-f23a-41a8-a140-01abaa31c931 | Integrated Taxonomic Information System (ITIS)
3 | 39653f3e-8d6b-4a94-a202-859359c164c5 | Belgian Species List
4 | 2d59e5db-57ad-41ff-97d6-11f5fb264527 | World Register of Marine Species
5 | 0a2eaf0c-5504-4f48-a47f-c94229029dc8 | World Register of Introduced Marine Species (WRiMS)

**Comment by niconoe** [comment]
Yeah I agree @damianooldoni. It's generally a good practice to keep the IDs "opaque" to the user and let the database manage them (rather than use an external key such as GBIF's `datasetKey`).

**Comment by peterdesmet** [comment]
I also logged this for the GBIF API: https://github.com/gbif/gbif-api/issues/64
