### ISSUE TITLE
Add language filter as parameter

### ISSUE THREAD

**Issue by damianooldoni** [inbo/speciesbim#24]
While exploring #19, I found that English was not in the list of languages. Adding it is straightforward (for me or @niconoe) as up to now the list of languages is hardcoded in  [vernacular_names.populate_vernacular_names() #L66](https://github.com/inbo/speciesbim/blob/master/scripts/vernacular_names.py#L66).

However, I think it's better to add it as parameter to be passed to the main function. In this way, it will be straightforward also for users of our code in the future in case they want to add or remove languages (e.g. by adding German or removing English) can do it easily without searching in the lines.
It's actually a small easily solvable issue (I have actually already solved locally)
@peterdesmet, do you agree?

**Comment by peterdesmet** [comment]
Yes, agree. Use 2-letter iso code to pass language.

**Comment by peterdesmet** [comment]
Depending how it is implement at GBIF's side, choose either 2 or 3-letter language code.

**Comment by damianooldoni** [comment]
About the use of 2 or 3-letter language code, GBIF uses the 3-letter variant. I discussed this already with @niconoe in his PR, https://github.com/inbo/speciesbim/pull/14#issuecomment-662464833 where he explains why he chose for the 2-letter variants. I agreed with him about it at the end, especially due to the synonyms ('fra' and 'fre' for 'fr', `nld` and `dut` for `nl`). 

@peterdesmet , do you agree with us or do you prefer to still use 3 letter variant as returned by GBIF?

**Comment by peterdesmet** [comment]
2 letter is fine 👌

**Comment by damianooldoni** [comment]
Solved in #25
