### ISSUE TITLE
Implement a demo mode for some functions

### ISSUE THREAD

**Issue by damianooldoni** [inbo/speciesbim#30]
The idea of a demo mode arises from the need of writing a notebook to document/demonstrate the functionalities developed in this repo (#21).

I list here below which steps (and corresponding function) could benefit of such demo mode which could be passed as an argument to the functions (`demo=True`). 

Main reason is that in this way we can select a very limited number of taxa covering all the possibilities (no matched names, exotic taxa, synonyms).

step | function | need of demo option
--- | --- | ---
Step 1: Drop our new tables if exist | sql snippet | NO
Step 2: Create new tables | sql snippet | NO
Step 3: populate the scientificname table | sql snippet | NO
Step 4: populate the scientificnameannex table | `populate_scientificname_annex` | YES
Step 5: populate taxonomy table with matches to GBIF | `gbif_match` | YES
Step 6: populate vernacular names | `populate_vernacular_names` | NO
Step 7: populate field exotic_be | `populate_is_exotic_be_field` | NO

How to implement this mode? By using two small txt (csv) files, one with some names from `scientificnameannex`, one with names from `scientificname` table.
Examples:
[scientificname_demo.txt](https://github.com/inbo/speciesbim/files/5128346/scientificname_demo.txt)
[official_annexes_demo.txt](https://github.com/inbo/speciesbim/files/5128347/official_annexes_demo.txt)

Something to be discussed in our weekly meeting today, I think.

**Comment by niconoe** [comment]
Hey @damianooldoni, can we close this issue or do you want to keep it open for more refinements to this feature?

**Comment by damianooldoni** [comment]
No, it is done. Thanks for reminding me!
