### ISSUE TITLE
Make the taxonomy table intolerant to duplicates

### ISSUE THREAD

**Issue by niconoe** [inbo/speciesbim#43]
Follow-up to #41: as a defensive measure, we should add constraints to the new taxonomy table doesn't accept any duplicate.

That will ensure not only that our import script doesn't currently add duplicated (#41), but also later on that the newly inserted data stays cleaner (than it is now)?.

**Comment by niconoe** [comment]
The issue seems less clear than I thought there, for several reasons:

- The discussions at #41 concerns the `scientificname` table, not this one.
- There's already a unique constraint on the `gbifId` field
- The `scientificName` field is populated by GBIF, and directly dependent on the value of `gbifId`
- As mentioned by @damianooldoni in another issue: the same scientific name might exist in different kingdoms. Thus, a unique constraint on `scientificName` could also create issues (except if we take into account the `parentId` - or the `kingdom`, but that's probably harder to implement.

I'd still like to have a defensive approach to make this table as future-proof as possible, but given all this I feel like the careful approach is probably to let this table unchanged for now (I still plan constraints on `scientificname`, though). @damianooldoni : any opinion about this?

**Comment by damianooldoni** [comment]
Thanks @niconoe for sharing these thoughts. 

- Indeed, the main issues about duplicates is all around `scientificname` table (see #41), not taxonomy. 
- the constraint on gbifID is indeed a good one
- the scientificName as stored in `taxonomy` includes authorship as this is the way it is stored by GBIF (see field `scientificName` in https://api.gbif.org/v1/species/5232437/) So, I don't see any danger in constraints on `scientificName` of `taxonomy` table. The only thing is: do we really need such a constraint in this table? I don't think so. Isn't `gbifId` enough?

**Comment by niconoe** [comment]
Agree, this is not needed at this point.
