### ISSUE TITLE
Implement a "quick mode" for transform_db.py

### ISSUE THREAD

**Issue by niconoe** [inbo/speciesbim#5]
Aim: limit the amount of data to make the whole process easily repeatable in development

Should be configurable via an entry in `config.ini`

**Comment by niconoe** [comment]
Update: I am implementing templating (Jinja-based) to SQL snippets. That will allow easily passing a `LIMIT` clause to the `populate_scientificname.sql` script, but I'm pretty sure the mechanism will be useful for other features too.

**Comment by damianooldoni** [comment]
I think this has been solved by giving the possibility to configure a limit in `config.ini`.
